### PR TITLE
Alice update

### PR DESCRIPTION
**Pull request by emmamarichal**
Hello! 

I'm Emma, and I work with @RosaWagner on font onboarding.

I checked Alice font, and made some changes according to Google's spec for the font update:

- v-metrics updated to fit with the old version
- OFL modified, RFN removed
- .notdef added, "Ellipsis" modified in the source file
- Font info updated (url links)

We removed the RFN because we are not supposed to publish the font with it, but if it is a problem, we can add it again after discussion.

Cheers,

### CODE REVIEW

**Comment by RosaWagner** [comment]
@alexeiva we would like to ship the upgrade to Google Fonts, can you take a look at this PR?

If you have questions about the changes (like the vertical metrics), I am happy to clarify.

**Comment by alexeiva** [comment]
> We removed the RFN because we are not supposed to publish the font with it, but if it is a problem, we can add it again after discussion.

This is fine. 

> If you have questions about the changes (like the vertical metrics), I am happy to clarify.

@RosaWagner can you elaborate on the v metrics changes?

> v-metrics updated to fit with the old version

By old version do you mean the current version on GF servers?

**Comment by RosaWagner** [comment]
> By old version do you mean the current version on GF servers?

Yes. We can't have different vertical metrics cause it would break all the websites already using the font through google fonts' API.

by "break" I mean that it would visually affect websites by messing up their layout.

**Comment by RosaWagner** [comment]
Thanks :)

**Pull request merged**
